package io.provenance.core

enum class KeyType {
    AUTHORIZATION_PUBLIC_KEY,
    AUTHORIZATION_PRIVATE_KEY,
    ENCRYPTION_PUBLIC_KEY,
    ENCRYPTION_PRIVATE_KEY,
    SIGNATURE_PUBLIC_KEY,
    SIGNATURE_PRIVATE_KEY,
    MNEMONIC,
}