name: Release and Publish

on:
  workflow_dispatch:
    inputs:
      versionModifier:
        description: Sem Version Modifier
        options:
          - patch
          - minor
          - major
        default: patch
        required: false
        type: choice

jobs:
  build:
    name: manual release and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build with Gradle
        if: ${{ github.ref_name == 'main' }}
        run: ./gradlew clean build --refresh-dependencies :generateVersionFile :createAndPushVersionTag githubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install gpg secret key
        run: |
          export GPG_TTY=$(tty)
          echo -n "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          echo -n "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode > $GITHUB_WORKSPACE/release.gpg

      - name: Publish to Maven Central
        run: |
          ./gradlew publishToSonatype -Psemver.modifier=${{ github.event.inputs.versionModifier }} $(if [ "${{github.event.release.prerelease}}" = "true" ]; then echo 'closeSonatypeStagingRepository'; else echo 'closeAndReleaseSonatypeStagingRepository'; fi) \
            -Psigning.keyId=B7D30ABE -Psigning.password="${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}" -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/release.gpg \
            --info
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}